### ISSUE TITLE
ERROR: chalk is not defined

### ISSUE THREAD

**Issue by mvvpavan** [akamai/cli-property#159]
akamai property create

ERROR:
         chalk is not defined

ReferenceError: chalk is not defined
    at errorMessage (/root/.akamai-cli/src/cli-property/bin/akamaiProperty:50:29)
    at TypeCommand.run [as _runHandler] (/root/.akamai-cli/src/cli-property/bin/akamaiProperty:475:20)
    at api.parseFromContext.then.whenDone (/root/.akamai-cli/src/cli-property/node_modules/sywac/types/command.js:130:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by synedra** [comment]
This is fixed
