### ISSUE TITLE
Can't update rule format for an existing property

### ISSUE THREAD

**Issue by jsequeir** [akamai/cli-property#208]
Hi team, 

Trying to run:
akamai property modify Joss_test2 --ruleformat v2020–11–02

I'm getting this error:

... searching propertyName for Joss_test2
... getting info for prp_667895
... retrieving property (Joss_test2) v4
... updating property (Joss_test2) v4
/Users/jsequeir/.akamai-cli/src/cli-property/src/website.js:826
                        if (response.statusCode >= 200 && response.statusCode < 400) {
                                     ^

TypeError: Cannot read property 'statusCode' of undefined
    at /Users/jsequeir/.akamai-cli/src/cli-property/src/website.js:826:38
    at EdgeGrid.<anonymous> (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:83:7)
    at self.callback (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.start (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/request/request.js:753:10)
    at Request.write (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/request/request.js:1497:10)
    at end (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/request/request.js:549:18)
    at Immediate.<anonymous> (/Users/jsequeir/.akamai-cli/src/cli-property/node_modules/request/request.js:578:7)
    at processImmediate (internal/timers.js:456:21)

Can someone point out the issue?

**Comment by akamaimike** [comment]
The Akamai CLI package 'property' has been deprecated in favor of the Akamai CLI package 'property-manager'. I recommend using this package instead. 

I notice you are trying to update the ruleFormat of a configuration. This is no longer supported as a stand-alone in both the Akamai API or the Akamai property-manager CLI. 

You would have to use property-update to create a new version and update the rule tree. Inside the JSON file you specify, you can set the "ruleFormat": "v2020-11-02". Running the command:
akamai property-manager property-update -p 'yourpropertyid' --file 'locationofyourfile'

This would update the rule format with the Akamai property-manager CLI.
