### ISSUE TITLE
List property variables failing

### ISSUE THREAD

**Issue by dmcallis1** [akamai/cli-property#51]
Following the last CLI update, I'm unable to pull variables (--variables flag) on retrieve actions:

atl-mp43o:~ dmcallis$ akamai property retrieve dm-lab.akamaized.net --variables
ERROR:  ReferenceError: retrieveVariables is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
ReferenceError: retrieveVariables is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3

**Comment by synedra** [comment]
This is resolved, my apologies.
