### ISSUE TITLE
Cannot deactivate

### ISSUE THREAD

**Issue by AstinCHOI** [akamai/cli-property#52]
My credential is okay, I can do all CLI commands except "deactivate"

* ENV
$ node --version
v8.9.4

* COMMAND
$ akamai property deactivate astin.ion.standard --network staging

 * ERROR
ERROR:  ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3

**Comment by synedra** [comment]
This was recently fixed – can you try Akamai update property?

Kirsten

**Comment by AstinCHOI** [comment]
After update, I see it works ! Thank you !!

**Comment by jmasisp** [comment]
Hi.
Even after update I'm unable to deactivate. 
All other commands work correctly. 

akamai upgrade property
Checking for upgrades...... [OK]
Akamai CLI (v0.4.2) is already up-to-date

 akamai property deactivate juanmasis.newhirelab.com --network STAGING
ERROR:  ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3

**Comment by synedra** [comment]
The command you want is update, not upgrade.  Please give that a try.

Kirsten

Sent from my iPhone

On Jan 12, 2018, at 8:49 AM, jmasisp <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi.
Even after update I'm unable to deactivate.
All other commands work correctly.

akamai upgrade property
Checking for upgrades...... [OK]
Akamai CLI (v0.4.2) is already up-to-date

akamai property deactivate juanmasis.newhirelab.com<http://juanmasis.newhirelab.com> --network STAGING
ERROR: ReferenceError: options is not defined
at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
at
at process._tickCallback (internal/process/next_tick.js:188:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
at startup (bootstrap_node.js:223:16)
at bootstrap_node.js:644:3
ReferenceError: options is not defined
at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
at
at process._tickCallback (internal/process/next_tick.js:188:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
at startup (bootstrap_node.js:223:16)
at bootstrap_node.js:644:3

-

**Comment by jmasisp** [comment]
Thanks for the correction but no luck.

akamai update property
Attempting to update "property" command...... [OK]
command "property" already up-to-date

then:

akamai property deactivate juanmasis.newhirelab.com --network staging --section default
ERROR:  ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
ReferenceError: options is not defined
    at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3

I did get a warning when updating.  node.js runtime missing, so, I installed binary. Should deactivate still work?

Installing...... [WARN]
Unable to locate Node.js runtime
Binary command(s) found, would you like to try download and install it? (Y/n): y

**Comment by synedra** [comment]
You should be good with the current binary, you may have had an older version.  Give the update a try again, deactivate should definitely work.

**Comment by jmasisp** [comment]
It’s working now. Just wanted to confirm. Thanks.

**Comment by synedra** [comment]
My apologies, the binary had gotten out of sync with the main codebase.  I’ve fixed and
downloaded the binary to test and it should be behaving now.

Thanks,
Kirsten



On January 12, 2018 at 11:17:40 AM, jmasisp (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks for the correction but no luck.

akamai update property
Attempting to update "property" command...... [OK]
command "property" already up-to-date

then:

akamai property deactivate juanmasis.newhirelab.com --network staging --section default
ERROR: ReferenceError: options is not defined
at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
at
at process._tickCallback (internal/process/next_tick.js:188:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
at startup (bootstrap_node.js:223:16)
at bootstrap_node.js:644:3
ReferenceError: options is not defined
at TypeCommand.run [as _runHandler] (/snapshot/cli-property/bin/akamaiProperty:0:0)
at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/cli-property/node_modules/sywac/types/command.js:130:19)
at
at process._tickCallback (internal/process/next_tick.js:188:7)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
at startup (bootstrap_node.js:223:16)
at bootstrap_node.js:644:3

I did get a warning when updating. node.js runtime missing, so, I installed binary. Should deactivate still work?

Installing...... [WARN]
Unable to locate Node.js runtime
Binary command(s) found, would you like to try download and install it? (Y/n): y
