### ISSUE TITLE
akamai property modify xx --addhosts xx  gives ERROR:  TypeError: Cannot read property 'productId' of undefined

### ISSUE THREAD

**Issue by lucdouwen** [akamai/cli-property#86]
Hi,

After updating the cli I kept getting the error 'TypeError: Cannot read property 'productId' of undefined' running the command 'akamai property modify xx --addhosts xx'
Akamai support advised us to open an issue here with the following solution : 
The product tied to ourcontract is prd_Site_Accel which is NOT matching any list in the above line 364.
The solution to fix this issue is to edit website.js line 364 to add "prd_Site_Accel" into the Array within the "If" statement.

Regards,
Luc 

Addendum 

C:\Users\lucd>akamai update
Attempting to update "appsec" command...... [OK]
command "appsec" already up-to-date
Attempting to update "snippets" command...... [OK]
command "snippets" already up-to-date
Attempting to update "pipeline" command...... [OK]
command "pipeline" already up-to-date
Attempting to update "property" command...... [OK]
command "property" already up-to-date
Attempting to update "snippets" command...... [OK]
command "snippets" already up-to-date
Attempting to update "pipeline" command...... [OK]
command "pipeline" already up-to-date

C:\Users\lucd>akamai property modify nonprod.papitest --addhosts test2.vlaanderen.be --edgehostname mvg.edgekey.net --origin test2origin.vlaanderen.be --forward incoming
... searching propertyName for nonprod.papitest
... getting info for prp_501650
... retrieving list of Products for this contract
ERROR:  TypeError: Cannot read property 'productId' of undefined
    at _getProperty.then.then.product (C:\Users\lucd\.akamai-cli\src\cli-property\src\website.js:1904:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'productId' of undefined
    at _getProperty.then.then.product (C:\Users\lucd\.akamai-cli\src\cli-property\src\website.js:1904:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

C:\Users\lucd>akamai upgrade
Checking for upgrades...... [OK]
Akamai CLI (v1.0.2) is already up-to-date
C:\Users\lucd>akamai property modify nonprod.papitest --addhosts test2.vlaanderen.be --edgehostname mvg.edgekey.net --origin test2origin.vlaanderen.be --forward incoming
... searching propertyName for nonprod.papitest
... getting info for prp_501650
... retrieving list of Products for this contract
ERROR:  TypeError: Cannot read property 'productId' of undefined
    at _getProperty.then.then.product (C:\Users\lucd\.akamai-cli\src\cli-property\src\website.js:1904:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)TypeError: Cannot read property 'productId' of undefined
    at _getProperty.then.then.product (C:\Users\lucd\.akamai-cli\src\cli-property\src\website.js:1904:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by synedra** [comment]
This is complete.
