### ISSUE TITLE
Error: An error occurred parsing the .edgerc file

### ISSUE THREAD

**Issue by ehues** [akamai/cli-property#89]
I've authorized my client with `akamai auth setup`. According to `akamai auth verify`:
```
$ akamai auth verify
Credential Name: ehughes client
---------------------------------
Created 2018-11-28T19:33:47Z by ehughes
Updated 2018-11-28T19:33:47Z by ehughes
Activated 2018-11-28T19:33:47Z by ehughes
Grants:
    adaptive-acceleration : readwrite
    papi : readwrite
```

When I try to get list of properties, I get
```
$ akamai property groups
ERROR:  Error: An error occurred parsing the .edgerc file. You probably specified an invalid section name.
    at module.exports (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/edgerc.js:111:11)
    at EdgeGrid._setConfigFromObj (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:154:17)
    at new EdgeGrid (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:27:10)
    at new WebSite (/snapshot/khunter/.akamai-cli/src/cli-property/src/website.js:0:0)
    at TypeCommand.run [as _runHandler] (/snapshot/khunter/.akamai-cli/src/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
Error: An error occurred parsing the .edgerc file. You probably specified an invalid section name.
    at module.exports (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/edgerc.js:111:11)
    at EdgeGrid._setConfigFromObj (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:154:17)
    at new EdgeGrid (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/edgegrid/src/api.js:27:10)
    at new WebSite (/snapshot/khunter/.akamai-cli/src/cli-property/src/website.js:0:0)
    at TypeCommand.run [as _runHandler] (/snapshot/khunter/.akamai-cli/src/cli-property/bin/akamaiProperty:0:0)
    at Type.postParse.context.api.parseFromContext.then.whenDone (/snapshot/khunter/.akamai-cli/src/cli-property/node_modules/sywac/types/command.js:130:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
```

~/.edgerc contains:
```
[default]
client_secret = ...
client_token = ...
access_token = ...
host = ...
```

**Comment by lukaszczerpak** [comment]
The property cli is looking for `papi` section name by default and I agree this is confusing as there is no good reason to use a separate name. 

```
❯ akamai property --help
Usage: akamai property <command> <args> [options]

Commands:
...

Command options:
  --config <config>    Config file               [file] [default: /Users/lczerpak/.edgerc]
  --section <section>  Config section                             [string] [default: papi]
```

The only exception currently should be (and it is) the purge cli for which a separate credentials are always provisioned and it's looking for `ccu` section by default - which makes a lot of sense.

**Comment by ehues** [comment]
Thanks @lukaszczerpak! 

```
akamai property groups --section default
```

produced output that looks reasonable. 

Would it be reasonable to ask that the property command switch to use the `default` section?

**Comment by lukaszczerpak** [comment]
I think PAPI falls into GENERAL API option when provisioning API credentials. Only CCU needs a separate client to be provisioned and as such makes sense to use different section name than `default`.

@synedra what's your opinion?

**Comment by synedra** [comment]
We encourage customers to create credentials for each of the actions they want to do.  A global credential is a huge security hole.  The 'help' does mention that the default is 'papi'...
